export const CHARACTER_PROFILES = {
  rhea:{origin:'SEOUL · KOREA',role:'TACTICAL CAPTAIN',tagline:'Calm water. Clean decisions.',bio:'A composed team leader who reads pressure before it arrives. Rhea favors balanced lines and controlled acceleration.',face:{shape:'oval',jaw:.88,cheek:.96,brow:.9,nose:.92,head:[.96,1.03,.96]},build:{height:1.01,shoulder:.98,chest:.96,waist:.82,hip:.92,arm:1,leg:1,muscle:.56},hair:{style:'bob',color:0x17161b},helmet:'open-aero',gear:'technical',stance:{lean:.92,elbow:.88,knee:.92},victory:'salute',voice:'measured',seed:1},
  kai:{origin:'LOS ANGELES · USA',role:'STREET SPRINTER',tagline:'Commit early. Exit faster.',bio:'An instinctive charger with explosive starts and a taste for risky overtakes. Kai rides forward on the bars and attacks every gap.',face:{shape:'angular',jaw:1.08,cheek:.9,brow:1.12,nose:1.04,head:[.99,1.01,.96]},build:{height:1.06,shoulder:1.12,chest:1.08,waist:.91,hip:.96,arm:1.04,leg:1.04,muscle:.82},hair:{style:'undercut',color:0x18120f},helmet:'full-race',gear:'street-armored',stance:{lean:1.2,elbow:1.08,knee:1.05},victory:'fist',voice:'bold',seed:2},
  sol:{origin:'BARCELONA · SPAIN',role:'LINE ENGINEER',tagline:'Speed is geometry.',bio:'A technical rider obsessed with perfect entry angles. Sol is quiet, analytical and devastating when a course rewards precision.',face:{shape:'long',jaw:.94,cheek:.88,brow:1.02,nose:1.08,head:[.94,1.08,.94]},build:{height:1.08,shoulder:.97,chest:.93,waist:.82,hip:.9,arm:1.06,leg:1.09,muscle:.46},hair:{style:'wavy',color:0x3b251a},helmet:'open-aero',gear:'minimal-tech',stance:{lean:1.03,elbow:.83,knee:.9},victory:'point',voice:'precise',seed:3},
  mina:{origin:'OSAKA · JAPAN',role:'DRIFT ARTIST',tagline:'Leave a signature in the wake.',bio:'Mina treats every corner like choreography. Her relaxed shoulders and low center of gravity make long slides look effortless.',face:{shape:'heart',jaw:.82,cheek:1.04,brow:.9,nose:.86,head:[.95,1.01,.98]},build:{height:.94,shoulder:.88,chest:.88,waist:.76,hip:.94,arm:.95,leg:.94,muscle:.42},hair:{style:'ponytail',color:0x101318},helmet:'open-sport',gear:'drift-layered',stance:{lean:.84,elbow:.76,knee:1.12},victory:'wave',voice:'playful',seed:4},
  jax:{origin:'CAPE TOWN · SOUTH AFRICA',role:'HEAVY WATER',tagline:'The wave moves first. I move last.',bio:'A powerful endurance specialist who stays composed in rough water. Jax uses body mass and hull stability to hold impossible lines.',face:{shape:'square',jaw:1.2,cheek:1.02,brow:1.1,nose:1.08,head:[1.04,1.02,1.02]},build:{height:1.1,shoulder:1.24,chest:1.18,waist:1.02,hip:1.05,arm:1.07,leg:1.05,muscle:1},hair:{style:'close',color:0x14100e},helmet:'full-heavy',gear:'armored-vest',stance:{lean:.72,elbow:1.14,knee:.84},victory:'chest',voice:'deep',seed:5},
  nari:{origin:'BUSAN · KOREA',role:'BOOST SPECIALIST',tagline:'Hold your breath. Then disappear.',bio:'Nari grew up around harbor racing and understands acceleration by sound. She is light on the hull and brutal on boost timing.',face:{shape:'oval',jaw:.87,cheek:.98,brow:.93,nose:.9,head:[.94,1.02,.95]},build:{height:.97,shoulder:.9,chest:.9,waist:.75,hip:.9,arm:.97,leg:.99,muscle:.48},hair:{style:'high-bun',color:0x201716},helmet:'open-aero',gear:'speed-shell',stance:{lean:1.18,elbow:.82,knee:.96},victory:'double-fist',voice:'bright',seed:6},
  omar:{origin:'ALEXANDRIA · EGYPT',role:'WAVE READER',tagline:'Water tells you what comes next.',bio:'Omar studies swell patterns and wind texture. His upright stance looks conservative until the sea turns violent and everyone else slows down.',face:{shape:'angular',jaw:1.04,cheek:.95,brow:1.08,nose:1.12,head:[.99,1.04,.98]},build:{height:1.07,shoulder:1.09,chest:1.02,waist:.9,hip:.96,arm:1.04,leg:1.06,muscle:.72},hair:{style:'curls',color:0x17110f},helmet:'open-sport',gear:'ocean-vest',stance:{lean:.68,elbow:.94,knee:.82},victory:'salute',voice:'warm',seed:7},
  yuna:{origin:'SINGAPORE',role:'ITEM TACTICIAN',tagline:'Luck favors preparation.',bio:'A systems-minded competitor who wins through timing, pickups and route awareness. Yuna is expressive off the water and calculating on it.',face:{shape:'heart',jaw:.84,cheek:1.03,brow:.94,nose:.88,head:[.95,1.01,.96]},build:{height:.95,shoulder:.89,chest:.89,waist:.76,hip:.92,arm:.96,leg:.96,muscle:.4},hair:{style:'braid',color:0x1a1312},helmet:'open-aero',gear:'utility-tech',stance:{lean:.9,elbow:.78,knee:.92},victory:'wave',voice:'quick',seed:8},
  theo:{origin:'RIO DE JANEIRO · BRAZIL',role:'LAUNCH CONTROL',tagline:'Win the first five seconds.',bio:'Theo lives for the start line. His athletic stance and aggressive weight transfer create explosive launches and dramatic recoveries.',face:{shape:'oval',jaw:1,cheek:.98,brow:1.04,nose:1,head:[.98,1.02,.97]},build:{height:1.05,shoulder:1.1,chest:1.06,waist:.88,hip:.95,arm:1.02,leg:1.06,muscle:.8},hair:{style:'locs',color:0x18100e},helmet:'open-sport',gear:'sprint-vest',stance:{lean:1.23,elbow:1.02,knee:1.04},victory:'fist',voice:'energetic',seed:9},
  amara:{origin:'LAGOS · NIGERIA',role:'DEFENSE CAPTAIN',tagline:'Stay visible. Stay standing.',bio:'Amara controls space with patient positioning and defensive tools. Her posture is centered, economical and almost impossible to unsettle.',face:{shape:'square',jaw:1.05,cheek:1.02,brow:1.02,nose:1.03,head:[.99,1.03,1]},build:{height:1.06,shoulder:1.12,chest:1.08,waist:.9,hip:1,arm:1.03,leg:1.03,muscle:.76},hair:{style:'braided-bun',color:0x100d0c},helmet:'full-race',gear:'guardian',stance:{lean:.78,elbow:1,knee:.86},victory:'crossed',voice:'commanding',seed:10},
  ren:{origin:'VANCOUVER · CANADA',role:'PRECISION PILOT',tagline:'No wasted movement.',bio:'Ren is a minimalist rider with clean inputs and a near-motionless upper body. Their advantage is consistency under pressure.',face:{shape:'long',jaw:.91,cheek:.9,brow:.96,nose:.96,head:[.94,1.07,.94]},build:{height:1.02,shoulder:.94,chest:.92,waist:.8,hip:.91,arm:1.02,leg:1.03,muscle:.5},hair:{style:'swept',color:0x25201f},helmet:'open-aero',gear:'precision',stance:{lean:.96,elbow:.74,knee:.88},victory:'point',voice:'quiet',seed:11},
  luz:{origin:'MEXICO CITY · MEXICO',role:'WILDCARD',tagline:'Plans are slower than instinct.',bio:'Luz changes rhythm constantly, baiting rivals into bad decisions. Her asymmetrical gear and animated riding style are impossible to ignore.',face:{shape:'heart',jaw:.88,cheek:1.08,brow:1.08,nose:.94,head:[.96,1.02,.98]},build:{height:.98,shoulder:.96,chest:.94,waist:.8,hip:.96,arm:.99,leg:.99,muscle:.55},hair:{style:'side-shave',color:0x2b1513},helmet:'open-sport',gear:'asymmetric',stance:{lean:1.03,elbow:.94,knee:1.08},victory:'dance',voice:'wild',seed:12},
  haneul:{origin:'JEJU · KOREA',role:'AERIAL SPECIALIST',tagline:'The fastest line is sometimes above the water.',bio:'Haneul grew up jumping coastal swell. Long limbs and a flexible stance let him absorb landings and redirect in the air.',face:{shape:'oval',jaw:.93,cheek:.94,brow:.96,nose:.95,head:[.96,1.04,.95]},build:{height:1.12,shoulder:1.02,chest:.98,waist:.84,hip:.92,arm:1.12,leg:1.14,muscle:.6},hair:{style:'windswept',color:0x18191c},helmet:'full-aero',gear:'aerial',stance:{lean:1.02,elbow:.9,knee:1.22},victory:'double-fist',voice:'calm',seed:13},
  mako:{origin:'AUCKLAND · NEW ZEALAND',role:'CURRENT HUNTER',tagline:'Use the ocean, never fight it.',bio:'Mako combines surfing instincts with mechanical discipline. He rides loose in cross-current and tightens only when the hull bites.',face:{shape:'square',jaw:1.12,cheek:1,brow:1.05,nose:1.06,head:[1.02,1.02,1]},build:{height:1.08,shoulder:1.16,chest:1.1,waist:.96,hip:1.02,arm:1.06,leg:1.07,muscle:.86},hair:{style:'long-tie',color:0x18110f},helmet:'open-heavy',gear:'current-vest',stance:{lean:.75,elbow:1.08,knee:.92},victory:'chest',voice:'grounded',seed:14},
  ivy:{origin:'LONDON · UK',role:'CONTROL SPECIALIST',tagline:'Control the line. Control the race.',bio:'Ivy is a disciplined tactician with a fashion-forward technical suit. Her riding position is compact and highly responsive.',face:{shape:'angular',jaw:.9,cheek:.92,brow:1.12,nose:.92,head:[.94,1.04,.95]},build:{height:.99,shoulder:.91,chest:.91,waist:.75,hip:.91,arm:.98,leg:1,muscle:.46},hair:{style:'sharp-bob',color:0x2a2026},helmet:'full-aero',gear:'couture-tech',stance:{lean:1.08,elbow:.78,knee:.96},victory:'crossed',voice:'cool',seed:15},
  zane:{origin:'DUBAI · UAE',role:'HUNTER',tagline:'Pick a target. Remove the distance.',bio:'Zane specializes in pursuit and psychological pressure. His broad stance and dark equipment make him look closer than he is.',face:{shape:'angular',jaw:1.14,cheek:.94,brow:1.15,nose:1.08,head:[1.01,1.03,.98]},build:{height:1.09,shoulder:1.18,chest:1.12,waist:.95,hip:.99,arm:1.07,leg:1.06,muscle:.9},hair:{style:'close',color:0x14100e},helmet:'full-heavy',gear:'hunter',stance:{lean:1.1,elbow:1.08,knee:.98},victory:'point',voice:'low',seed:16}
};

export function getCharacterProfile(id){
  return CHARACTER_PROFILES[id] || CHARACTER_PROFILES.rhea;
}

export const CHARACTER_PIPELINE = {
  version:15,
  heroLod:'LOD0 facial rig + layered gear + articulated limbs',
  rivalLod:'LOD1 simplified face + full articulated silhouette',
  requiredBones:['root','pelvis','spine','chest','neck','head','upperArm.L','foreArm.L','hand.L','upperArm.R','foreArm.R','hand.R','upperLeg.L','lowerLeg.L','boot.L','upperLeg.R','lowerLeg.R','boot.R'],
  animationStates:['menu-idle','ride','hard-turn','drift','boost','landing','victory'],
  replacementFormat:'GLB / Draco / KTX2 / Meshopt'
};
