import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { validateEnabledRiders } from './rider-glb-validator.mjs';

const root=process.cwd(),sha256=file=>crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex'),readJson=file=>JSON.parse(fs.readFileSync(file,'utf8'));
const rel=file=>path.relative(root,file).replaceAll('\\','/'),exists=file=>fs.existsSync(path.join(root,file));

export function runReleaseAudit({runTests=false,write=false}={}){
  const policy=readJson(path.join(root,'release/release-policy.json')),manifest=readJson(path.join(root,'assets/manifest.json')),checks=[];
  const add=(id,ok,severity,evidence)=>checks.push({id,ok:Boolean(ok),severity,evidence});
  const missingRequired=policy.requiredFiles.filter(file=>!exists(file));add('required-files',missingRequired.length===0,'blocker',missingRequired.length?`missing: ${missingRequired.join(', ')}`:`${policy.requiredFiles.length} required files present`);
  let vendorVersion='missing';try{vendorVersion=readJson(path.join(root,'vendor/three/package.json')).version}catch{}add('three-runtime-license',vendorVersion==='0.185.0'&&exists('vendor/three/LICENSE'),'blocker',`three=${vendorVersion}; license=${exists('vendor/three/LICENSE')}`);
  const runtimeText=policy.sourceFiles.filter(exists).map(file=>fs.readFileSync(path.join(root,file),'utf8')).join('\n'),remoteRuntime=[...runtimeText.matchAll(/(?:src=|href=|from\s*|import\s*\()\s*["'`](https?:\/\/[^"'`\s]+)/g)].map(match=>match[1]);add('no-remote-runtime',remoteRuntime.length===0,'blocker',remoteRuntime.length?remoteRuntime:'all executable/runtime references are local');
  const assetRefs=[...new Set([...runtimeText.matchAll(/["'`](\.\/assets\/[^"'`$?]+)["'`]/g)].map(match=>match[1].replace(/^\.\//,'')))],missingRefs=assetRefs.filter(file=>!exists(file));add('referenced-assets-exist',missingRefs.length===0,'blocker',missingRefs.length?missingRefs:`${assetRefs.length} literal asset references resolved`);
  const enabled=manifest.assets.filter(asset=>asset.enabled!==false),badEnabled=enabled.filter(asset=>{const relative=asset.url?.replace(/^\.\//,'');return!relative||!exists(relative)||!asset.source||!asset.license||!asset.sha256||(exists(relative)&&sha256(path.join(root,relative))!==asset.sha256)});add('enabled-assets-provenance',badEnabled.length===0,'blocker',badEnabled.length?badEnabled.map(asset=>asset.id):`${enabled.length} enabled manifest assets verified with matching hashes`);
  const riderEntries=manifest.assets.filter(asset=>asset.category==='rider'),productionRiders=riderEntries.filter(asset=>asset.enabled!==false&&exists(asset.url.replace(/^\.\//,''))),riderValidation=validateEnabledRiders(root,manifest),badRiders=riderValidation.filter(result=>!result.ok);add('premium-rider-lod0',productionRiders.length>=policy.requiredRiderLod0&&badRiders.length===0,'blocker',`${productionRiders.length}/${policy.requiredRiderLod0} enabled rider LOD0 files; ${badRiders.length} invalid rigs${badRiders.length?`: ${badRiders.map(result=>result.id).join(', ')}`:''}`);
  const premiumRuntimeSignals=['SkeletonUtils.js','upgradeCraftRider','AnimationMixer','premiumClipForState','proceduralRiderRoot'],missingPremiumRuntime=premiumRuntimeSignals.filter(signal=>!runtimeText.includes(signal));add('premium-rider-runtime',missingPremiumRuntime.length===0,'blocker',missingPremiumRuntime.length?`missing runtime signals: ${missingPremiumRuntime.join(', ')}`:'skinned clone, authored clips, crossfade upgrade and procedural fallback are integrated');
  let provenanceOk=true,provenanceEvidence='unreadable';try{const provenance=readJson(path.join(root,'assets/textures/polyhaven/provenance.json')),bad=provenance.files.filter(item=>!exists(`assets/textures/polyhaven/${item.file}`)||sha256(path.join(root,'assets/textures/polyhaven',item.file))!==item.sha256);provenanceOk=provenance.license==='CC0'&&bad.length===0;provenanceEvidence=`${provenance.files.length-bad.length}/${provenance.files.length} hashes; license=${provenance.license}`}catch{}add('polyhaven-provenance',provenanceOk,'blocker',provenanceEvidence);
  let generatedOk=true,generatedEvidence='unreadable';try{const provenance=readJson(path.join(root,'assets/textures/generated-provenance.json')),bad=provenance.files.filter(item=>!exists(`assets/textures/${item.file}`)||sha256(path.join(root,'assets/textures',item.file))!==item.sha256||!item.source||!item.promptSummary);generatedOk=provenance.tool==='OpenAI built-in image generation'&&bad.length===0;generatedEvidence=`${provenance.files.length-bad.length}/${provenance.files.length} generated texture hashes and sources verified`}catch{}add('generated-texture-provenance',generatedOk,'blocker',generatedEvidence);
  const notices=exists('assets/THIRD_PARTY_NOTICES.md')?fs.readFileSync(path.join(root,'assets/THIRD_PARTY_NOTICES.md'),'utf8'):'';add('third-party-notices',/Poly Haven/i.test(notices)&&/Three\.js/i.test(notices),'blocker','Poly Haven and Three.js notices required');
  let publisher=null;try{publisher=readJson(path.join(root,'release/publisher.json'))}catch{}const publisherOk=publisher&&['legalName','country','supportEmail','privacyContact','copyright'].every(key=>publisher[key]&&!/REPLACE_WITH/i.test(publisher[key]));add('publisher-identity',publisherOk,'blocker',publisherOk?publisher.legalName:'release/publisher.json is missing or contains placeholders');
  let commercialApproval=null;try{commercialApproval=readJson(path.join(root,'release/commercial-approval.json'))}catch{}const legalFiles=['release/EULA.md','release/PRIVACY.md','release/SUPPORT_POLICY.md'],missingLegal=legalFiles.filter(file=>!exists(file)),unapprovedLegal=legalFiles.filter(exists).filter(file=>/REPLACE_WITH|REVIEW TEMPLATE|\bDRAFT\b/i.test(fs.readFileSync(path.join(root,file),'utf8'))),approvalFlags=['eulaApproved','privacyApproved','supportPolicyApproved','refundDisclosureApproved','ageRatingApproved','trademarkReviewCompleted','marketingRightsReviewed'],approvalOk=commercialApproval&&approvalFlags.every(key=>commercialApproval[key]===true)&&commercialApproval.publisherLegalName&&!/REPLACE_WITH/i.test(commercialApproval.publisherLegalName)&&commercialApproval.legalReviewer&&!/REPLACE_WITH/i.test(commercialApproval.legalReviewer)&&commercialApproval.signature&&!/REPLACE_WITH/i.test(commercialApproval.signature)&&!Number.isNaN(Date.parse(commercialApproval.approvedAt))&&Array.isArray(commercialApproval.territories)&&commercialApproval.territories.length>0&&Array.isArray(commercialApproval.storefronts)&&commercialApproval.storefronts.length>0&&commercialApproval.ageRating&&!/REPLACE_WITH/i.test(commercialApproval.ageRating)&&commercialApproval.price>0&&/^[A-Z]{3}$/.test(commercialApproval.currency);add('commercial-legal-approval',missingLegal.length===0&&unapprovedLegal.length===0&&approvalOk,'blocker',missingLegal.length||unapprovedLegal.length||!approvalOk?{missingLegal,unapprovedLegal,approval:'release/commercial-approval.json missing or incomplete'}:`${commercialApproval.publisherLegalName}; ${commercialApproval.territories.length} territories; ${commercialApproval.storefronts.length} storefronts approved`);
  const forbidden=[];for(const folder of['assets','v18','v17','v16','v14']){if(!exists(folder))continue;const walk=dir=>{for(const entry of fs.readdirSync(dir,{withFileTypes:true})){const file=path.join(dir,entry.name);if(entry.isDirectory())walk(file);else if(/\.(?:psd|blend\d*|fbx|max|ma|mb|wav\.tmp)$/i.test(entry.name))forbidden.push(rel(file))}};walk(path.join(root,folder))}add('no-source-art-leaks',forbidden.length===0,'blocker',forbidden.length?forbidden:'no forbidden source-art files');
  const webFiles=[];for(const folder of['assets','v18','v17','v16','v14','vendor']){if(!exists(folder))continue;const walk=dir=>{for(const entry of fs.readdirSync(dir,{withFileTypes:true})){const file=path.join(dir,entry.name);entry.isDirectory()?walk(file):webFiles.push(file)}};walk(path.join(root,folder))}for(const file of ['index.html','data-v12.js','systems-v13.js'])if(exists(file))webFiles.push(path.join(root,file));const packageBytes=webFiles.reduce((sum,file)=>sum+fs.statSync(file).size,0);add('package-size-budget',packageBytes<=policy.maxPackageBytes,'blocker',`${(packageBytes/1048576).toFixed(2)} MiB / ${(policy.maxPackageBytes/1048576).toFixed(0)} MiB`);
  if(runTests){const suites=fs.readdirSync(path.join(root,'scripts')).filter(file=>/check\.mjs$/i.test(file)).sort(),failed=[];for(const suite of suites){const result=spawnSync(process.execPath,[path.join(root,'scripts',suite)],{cwd:root,encoding:'utf8'});if(result.status!==0)failed.push({suite,status:result.status,stderr:(result.stderr||'').slice(-500)})}add('automated-regression',failed.length===0,'blocker',failed.length?failed:`${suites.length}/${suites.length} suites passed`)}else add('automated-regression',false,'warning','not executed; pass --tests');
  let playtest=null;try{playtest=readJson(path.join(root,'release/playtest-matrix.json'))}catch{}const playtestFailures=[],sessions=Array.isArray(playtest?.sessions)?playtest.sessions:[],targetResults=policy.requiredBrowserTargets.map(target=>{const [browser,minimumText]=target.split(/\s+/),minimum=Number.parseInt(minimumText,10),session=sessions.find(item=>item.browser===browser);if(!session){playtestFailures.push(`${browser}: missing session`);return false}const version=Number.parseInt(String(session.browserVersion),10),requiredBooleans=['passed','saveLoadRecovered','controlsVerified','gamepadVerified','accessibilityVerified','activityAndFishingVerified'];const valid=version>=minimum&&session.durationMinutes>=30&&session.crashes===0&&session.bootSeconds>0&&session.bootSeconds<=15&&session.p50FrameMs>0&&session.p95FrameMs>0&&session.p95FrameMs<=40&&requiredBooleans.every(key=>session[key]===true)&&session.tester&&!/REPLACE_WITH/i.test(session.tester)&&session.signature&&!/REPLACE_WITH/i.test(session.signature)&&!Number.isNaN(Date.parse(session.signedAt));if(!valid)playtestFailures.push(`${browser}: incomplete or failed evidence`);return valid}),hasIntegrated=sessions.some(session=>session.gpuClass==='integrated');if(!hasIntegrated)playtestFailures.push('integrated-GPU session missing');add('manual-browser-matrix',targetResults.every(Boolean)&&hasIntegrated,'blocker',playtestFailures.length?playtestFailures:`${targetResults.length}/${targetResults.length} signed 30-minute browser sessions passed, including integrated GPU`);
  const accessibilityFiles=['index.html','v18/main.js','v14/audio-director.js'].map(file=>fs.readFileSync(path.join(root,file),'utf8')).join('\n'),accessibilitySignals=['data-tab="settings"','setVolume(channel,value)','data-volume=','data-remap=','AUDIO_CAPTIONS','reduced-effects','high-contrast'],missingAccessibility=accessibilitySignals.filter(signal=>!accessibilityFiles.includes(signal));add('accessibility-settings',missingAccessibility.length===0,'blocker',missingAccessibility.length?`missing: ${missingAccessibility.join(', ')}`:'audio mixer, remapping, captions, reduced effects and high contrast are implemented');
  const blockers=checks.filter(check=>check.severity==='blocker'&&!check.ok),warnings=checks.filter(check=>check.severity==='warning'&&!check.ok),report={product:policy.product,version:policy.version,generatedAt:new Date().toISOString(),saleReady:blockers.length===0,summary:{passed:checks.filter(check=>check.ok).length,failed:checks.filter(check=>!check.ok).length,blockers:blockers.length,warnings:warnings.length},checks};
  if(write){fs.mkdirSync(path.join(root,'release'),{recursive:true});fs.writeFileSync(path.join(root,'release/RELEASE_AUDIT.json'),JSON.stringify(report,null,2)+'\n')}
  return report;
}

const isMain=process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url);if(isMain){const strict=process.argv.includes('--strict'),report=runReleaseAudit({runTests:process.argv.includes('--tests'),write:process.argv.includes('--write')});for(const check of report.checks)console.log(`${check.ok?'PASS':check.severity==='blocker'?'BLOCK':'WARN'} ${check.id} — ${typeof check.evidence==='string'?check.evidence:JSON.stringify(check.evidence)}`);console.log(`\nSALE READY=${report.saleReady} · PASS=${report.summary.passed} · BLOCKERS=${report.summary.blockers} · WARNINGS=${report.summary.warnings}`);if(strict&&!report.saleReady)process.exit(1)}
